### ISSUE TITLE
Can't recognize line breaks

### ISSUE THREAD

**Issue by ymtdzzz** [toolbox-labo/md-design-doc#13]
Only the rule that end with List can be recognized line breaks.

reproduction:

rule
```yml
doc:
  blocks:
    - block:
      - column: No
        isNum: true
      - group: Variation
        columns:
          - column: Variation 1
            md: Heading2
          - column: Variation 2
            md: Heading3
          - column: Variation 3
            md: Heading4
          - column: Variation 4
            md: Heading5
          - column: Variation 5
            md: Heading6
          - column: Variation 6
            md: Heading7
          - column: Variation 7
            md: Heading8
```

input
```markdown
# Sheet Name
## Test Variation 1
### Test Variation 1-1
#### Test Variation 1-1-1
### Test Variation 1-2
#### Test Variation 1-2-1
#### Test Variation 1-2-2
##### Test Variation 1-2-2-1
```

output

![Screenshot from 2021-01-25 21-02-48](https://user-images.githubusercontent.com/44557218/105703607-d88be000-5f50-11eb-9742-7a7b2065aea6.png)

Everything is printed on the same line!
