### ISSUE TITLE
Customizable parsing settings

### ISSUE THREAD

**Issue by ymtdzzz** [toolbox-labo/md-design-doc#2]
This tool is expected to support various design documents in the future.
So it's valuable to think early on how to make the parsing rule customizable.

In my opinion, the yaml or json are suitable.

**Comment by ymtdzzz** [comment]
yaml setting image:

```yml
# TODO: general settings
# general:
#   copyright: hogehoge
#   prefix: IT
doc:
  blocks:
    - block:
      - column: No
        isNum: true
      - group: Variation
        columns:
          - column: Variation 1
            md: Heading2
          - column: Variation 2
            md: Heading3
          - column: Variation 3
            md: Heading4
          - column: Variation 4
            md: Heading5
          - column: Variation 5
            md: Heading6
          - column: Variation 6
            md: Heading7
          - column: Variation 7
            md: Heading8
      - column: Description
        md: List
      # TODO: support variable list patterns
      #   customPrefix: "*"
      # - column: Procedure
      #   md: List
      # - column: Confirmation Items
      #   md: TaskList
    # TODO: multi blocks support
    # - block:
    #   - column: another block's column 1
    #     md: Heading2
    #   - column: another block's column 2
    #     md: Heading3
```
