### ISSUE TITLE
[Parser] Supporting various list settings

### ISSUE THREAD

**Issue by ymtdzzz** [toolbox-labo/md-design-doc#9]
rule

```yml
doc:
  blocks:
    - block:
      - column: No
        isNum: true
      - group: Variation
        columns:
          - column: Variation 1
            md: Heading2
          - column: Variation 2
            md: Heading3
          - column: Variation 3
            md: Heading4
          - column: Variation 4
            md: Heading5
          - column: Variation 5
            md: Heading6
          - column: Variation 6
            md: Heading7
          - column: Variation 7
            md: Heading8
      # various list support
      - column: Description
        md: List
        customPrefix: "*"
      - column: Procedure
        md: List
      - column: Confirmation Items
        md: TaskList
```

input

```markdown
# Sheet Name
## Test Variation 1
### Test Variation 1-1
#### Test Variation 1-1-1
* Test Description
  more lines...
  more lines...
- Procedure
  more procedure
  more procedure
- [ ] Confirmation Item
      more item
      more item
# this is also ok?
- Procedure
- more procedure
- more procedure
- [ ] Confirmation Item
- [ ] more item
- [ ] more item
```

output

![image](https://user-images.githubusercontent.com/44557218/105619387-8904c180-5e35-11eb-9884-31e5375e9a0f.png)
